{% set version = "0.29.2" %}

package:
  name: pkg-config
  version: {{ version }}

source:
  fn: pkg-config-{{ version }}.tar.gz
  url: https://pkg-config.freedesktop.org/releases/pkg-config-{{ version }}.tar.gz
  sha256: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591

build:
  skip: True  # [win]
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - automake

# TODO :: Add this back once we have freetype2 working (if it does not lead to
#         a dependency cycle).
# test:
#   commands:
#     - pkg-config --help
#     - '[ "$(pkg-config freetype2 --cflags)" == "-I$PREFIX/include/freetype2" ]'
#
#   requires:
#     - freetype

about:
  home: http://www.freedesktop.org/wiki/Software/pkg-config/
  license: GPL 2
  summary: Interface for querying installed libraries for use during compilation.

extra:
  recipe-maintainers:
    - jakirkham
    - mdboom
    - ocefpaf
    - tacaswell
    - mingwandroid
