appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lyViFD5Qj5Yp+FzdmUusJrm5I/GSdvp7kuYQLs/kScrHC3xH/u7TnuYqxSCm0tHr66Jyj9PdxAeODxQ7HNE+qJn3FuaFCvIEIk4F7/9cY0a3OCnSzvmiEi2BmioGZqqiIaNPyAvBzw4DutmQJaGYnWAIf5JHs0xCZZgMVh/XKVpkpYf1pn5AVXbqElL17nEKnXC7MTjUFcfam52F0MQRo1WYEWC+aSQdL6oKvW3IhMmCKIHs1Tj6o3JVHTtmIwi52hXtZ7GNb6UW67BDZw4zy5w34rTTLCdl3zbEXsOtt4kDC1qeVd0mJEOgg/1yGXq1W8w+D4M46l32bWbfJ1TerSomMrd/UgcQ2NX2RoHeqlTm0QrRUR2wqOIW37glH580CqFt3JMVvLTvh7kN8Ff9dWyGDBcUCaV4nw1J3sIGzCJKwXUzWisIpsdZbolznV0k/T9CQG5sNUxa17SJk8KYEaVrSs7ryWMFkIZmzFJ3MLTn0hXND5ymEf9LLtg1emZGgr6btWqxr2RM9ce5v9YthjkaY9N8K1Ym8LqdUWGmQ9U4n0BsC+MZ2xhVRR30DmyTI/VqLGo3Roch0qA+KRr2F82YRSXaVVelk4wsNCk5YrPvxijIfJt3Rd2c9FeHA5iDx31/HzX3sVVzcVf7WC6x2YxfQehmbZLWIVeXl+Wda6Y=}
